#ifndef STICKER_H
#define STICKER_H

#define MAX_STICKERS 980

typedef enum {
	MISSING = 0,
	HAVE = 1,
	DUPLICATE = 2
} Status;

typedef struct {
	Status status;
	int quantity;
	char name[];
	char code[]
	char team_code[];
} Sticker;

static const Sticker CATALOG[MAX_STICKERS] = {
    { MISSING, 0, "Panini Logo", "00", "P00" },
    { MISSING, 0, "Official Emblem1", "FWC1", "FWC" },
    { MISSING, 0, "Official Emblem2", "FWC2", "FWC" },
    { MISSING, 0, "Official Mascots", "FWC3", "FWC" },
    { MISSING, 0, "Official Slogan", "FWC4", "FWC" },
    { MISSING, 0, "Official Ball", "FWC5", "FWC" },
    { MISSING, 0, "Canada", "FWC6", "FWC" },
    { MISSING, 0, "Mexico", "FWC7", "FWC" },
    { MISSING, 0, "USA", "FWC8", "FWC" },
    { MISSING, 0, "Emblem", "MEX1", "MEX" },
    { MISSING, 0, "Luis Malagón", "MEX2", "MEX" },
    { MISSING, 0, "Johan Vasquez", "MEX3", "MEX" },
    { MISSING, 0, "Jorge Sánchez", "MEX4", "MEX" },
    { MISSING, 0, "Cesar Montes", "MEX5", "MEX" },
    { MISSING, 0, "Jesus Gallardo", "MEX6", "MEX" },
    { MISSING, 0, "Israel Reyes", "MEX7", "MEX" },
    { MISSING, 0, "Diego Lainez", "MEX8", "MEX" },
    { MISSING, 0, "Carlos Rodriguez", "MEX9", "MEX" },
    { MISSING, 0, "Edson Alvarez", "MEX10", "MEX" },
    { MISSING, 0, "Orbelin Pineda", "MEX11", "MEX" },
    { MISSING, 0, "Marcel Ruiz", "MEX12", "MEX" },
    { MISSING, 0, "Team Photo", "MEX13", "MEX" },
    { MISSING, 0, "Érick Sánchez", "MEX14", "MEX" },
    { MISSING, 0, "Hirving Lozano", "MEX15", "MEX" },
    { MISSING, 0, "Santiago Giménez", "MEX16", "MEX" },
    { MISSING, 0, "Raúl Jiménez", "MEX17", "MEX" },
    { MISSING, 0, "Alexis Vega", "MEX18", "MEX" },
    { MISSING, 0, "Roberto Alvarado", "MEX19", "MEX" },
    { MISSING, 0, "Cesar Huerta", "MEX20", "MEX" },
    { MISSING, 0, "Emblem", "RSA1", "RSA" },
    { MISSING, 0, "Ronwen Williams", "RSA2", "RSA" },
    { MISSING, 0, "Sipho Chaine", "RSA3", "RSA" },
    { MISSING, 0, "Aubrey Modiba", "RSA4", "RSA" },
    { MISSING, 0, "Samukele Kabini", "RSA5", "RSA" },
    { MISSING, 0, "Mbekezeli Mbokazi", "RSA6", "RSA" },
    { MISSING, 0, "Khulumani Ndamane", "RSA7", "RSA" },
    { MISSING, 0, "Siyabonga Ngezana", "RSA8", "RSA" },
    { MISSING, 0, "Khuliso Mudau", "RSA9", "RSA" },
    { MISSING, 0, "Nkosinathi Sibisi", "RSA10", "RSA" },
    { MISSING, 0, "Teboho Mokoena", "RSA11", "RSA" },
    { MISSING, 0, "Thalente Mbatha", "RSA12", "RSA" },
    { MISSING, 0, "Team Photo", "RSA13", "RSA" },
    { MISSING, 0, "Bathasi Aubaas", "RSA14", "RSA" },
    { MISSING, 0, "Yaya Sithole", "RSA15", "RSA" },
    { MISSING, 0, "Sipho Mbule", "RSA16", "RSA" },
    { MISSING, 0, "Lyle Foster", "RSA17", "RSA" },
    { MISSING, 0, "Iqraam Rayners", "RSA18", "RSA" },
    { MISSING, 0, "Mohau Nkota", "RSA19", "RSA" },
    { MISSING, 0, "Oswin Appollis", "RSA20", "RSA" },
    { MISSING, 0, "Emblem", "KOR1", "KOR" },
    { MISSING, 0, "Hyeon-woo Jo", "KOR2", "KOR" },
    { MISSING, 0, "Seung-Gyu Kim", "KOR3", "KOR" },
    { MISSING, 0, "Min-jae Kim", "KOR4", "KOR" },
    { MISSING, 0, "Yu-min Cho", "KOR5", "KOR" },
    { MISSING, 0, "Young-woo Seol", "KOR6", "KOR" },
    { MISSING, 0, "Han-beom Lee", "KOR7", "KOR" },
    { MISSING, 0, "Tae-seok Lee", "KOR8", "KOR" },
    { MISSING, 0, "Myung-jae Lee", "KOR9", "KOR" },
    { MISSING, 0, "Jae-sung Lee", "KOR10", "KOR" },
    { MISSING, 0, "In-beom Hwang", "KOR11", "KOR" },
    { MISSING, 0, "Kang-in Lee", "KOR12", "KOR" },
    { MISSING, 0, "Team Photo", "KOR13", "KOR" },
    { MISSING, 0, "Seung-ho Paik", "KOR14", "KOR" },
    { MISSING, 0, "Jens Castrop", "KOR15", "KOR" },
    { MISSING, 0, "Dongg-yeong Lee", "KOR16", "KOR" },
    { MISSING, 0, "Gue-sung Cho", "KOR17", "KOR" },
    { MISSING, 0, "Heung-min Son", "KOR18", "KOR" },
    { MISSING, 0, "Hee-chan Hwang", "KOR19", "KOR" },
    { MISSING, 0, "Hyeon-Gyu Oh", "KOR20", "KOR" },
    { MISSING, 0, "Emblem", "CZE1", "CZE" },
    { MISSING, 0, "Matej Kovar", "CZE2", "CZE" },
    { MISSING, 0, "Jindrich Stanek", "CZE3", "CZE" },
    { MISSING, 0, "Ladislav Krejci", "CZE4", "CZE" },
    { MISSING, 0, "Vladimir Coufal", "CZE5", "CZE" },
    { MISSING, 0, "Jaroslav Zeleny", "CZE6", "CZE" },
    { MISSING, 0, "Tomas Holes", "CZE7", "CZE" },
    { MISSING, 0, "David Zima", "CZE8", "CZE" },
    { MISSING, 0, "Michal Sadilek", "CZE9", "CZE" },
    { MISSING, 0, "Lukas Provod", "CZE10", "CZE" },
    { MISSING, 0, "Lukas Cerv", "CZE11", "CZE" },
    { MISSING, 0, "Tomas Soucek", "CZE12", "CZE" },
    { MISSING, 0, "Team Photo", "CZE13", "CZE" },
    { MISSING, 0, "Pavel Sulc", "CZE14", "CZE" },
    { MISSING, 0, "Matej Vydra", "CZE15", "CZE" },
    { MISSING, 0, "Vasil Kusej", "CZE16", "CZE" },
    { MISSING, 0, "Tomas Chory", "CZE17", "CZE" },
    { MISSING, 0, "Vaclav Cerny", "CZE18", "CZE" },
    { MISSING, 0, "Adam Hlozek", "CZE19", "CZE" },
    { MISSING, 0, "Patrik Schick", "CZE20", "CZE" },
    { MISSING, 0, "Emblem", "CAN1", "CAN" },
    { MISSING, 0, "Dayne St.Clair", "CAN2", "CAN" },
    { MISSING, 0, "Alphonso Davies", "CAN3", "CAN" },
    { MISSING, 0, "Alistair Johnston", "CAN4", "CAN" },
    { MISSING, 0, "Samuel Adekugbe", "CAN5", "CAN" },
    { MISSING, 0, "Riche Larvea", "CAN6", "CAN" },
    { MISSING, 0, "Derek Cornelius", "CAN7", "CAN" },
    { MISSING, 0, "Moïse Bombito", "CAN8", "CAN" },
    { MISSING, 0, "Kamal Miller", "CAN9", "CAN" },
    { MISSING, 0, "Stephen Eustáquio", "CAN10", "CAN" },
    { MISSING, 0, "Ismaël Koné", "CAN11", "CAN" },
    { MISSING, 0, "Jonathan Osorio", "CAN12", "CAN" },
    { MISSING, 0, "Team Photo", "CAN13", "CAN" },
    { MISSING, 0, "Jacob Shaffelburg", "CAN14", "CAN" },
    { MISSING, 0, "Mathieu Choinière", "CAN15", "CAN" },
    { MISSING, 0, "Niko Sigur", "CAN16", "CAN" },
    { MISSING, 0, "Tajon Buchanan", "CAN17", "CAN" },
    { MISSING, 0, "Liam Millar", "CAN18", "CAN" },
    { MISSING, 0, "Cyle Larin", "CAN19", "CAN" },
    { MISSING, 0, "Jonathan David", "CAN20", "CAN" },
    { MISSING, 0, "Emblem", "BIH1", "BIH" },
    { MISSING, 0, "Nikola Vasilj", "BIH2", "BIH" },
    { MISSING, 0, "Amer Dedic", "BIH3", "BIH" },
    { MISSING, 0, "Sead Kolasinac", "BIH4", "BIH" },
    { MISSING, 0, "Tarik Muharemovic", "BIH5", "BIH" },
    { MISSING, 0, "Nihad Mujakic", "BIH6", "BIH" },
    { MISSING, 0, "Nikola Katic", "BIH7", "BIH" },
    { MISSING, 0, "Amir Hadziahmetovic", "BIH8", "BIH" },
    { MISSING, 0, "Benjamin Tahirovic", "BIH9", "BIH" },
    { MISSING, 0, "Armin Gigovic", "BIH10", "BIH" },
    { MISSING, 0, "Ivan Sunjic", "BIH11", "BIH" },
    { MISSING, 0, "Ivan Basic", "BIH12", "BIH" },
    { MISSING, 0, "Team Photo", "BIH13", "BIH" },
    { MISSING, 0, "Dzenis Burnic", "BIH14", "BIH" },
    { MISSING, 0, "Esmir Bajraktarevic", "BIH15", "BIH" },
    { MISSING, 0, "Amar Memic", "BIH16", "BIH" },
    { MISSING, 0, "Ermedin Demirovic", "BIH17", "BIH" },
    { MISSING, 0, "Edin Dzeko", "BIH18", "BIH" },
    { MISSING, 0, "Samed Bazdar", "BIH19", "BIH" },
    { MISSING, 0, "Haris Tabakovic", "BIH20", "BIH" },
    { MISSING, 0, "Emblem", "QAT1", "QAT" },
    { MISSING, 0, "Meshaal Barsham", "QAT2", "QAT" },
    { MISSING, 0, "Sultan Albrake", "QAT3", "QAT" },
    { MISSING, 0, "Lucas Mendes", "QAT4", "QAT" },
    { MISSING, 0, "Homam Ahmed", "QAT5", "QAT" },
    { MISSING, 0, "Boualem Khoukhi", "QAT6", "QAT" },
    { MISSING, 0, "Pedro Miguel", "QAT7", "QAT" },
    { MISSING, 0, "Tarek Salman", "QAT8", "QAT" },
    { MISSING, 0, "Mohamed Al-Mannai", "QAT9", "QAT" },
    { MISSING, 0, "Karim Boudiaf", "QAT10", "QAT" },
    { MISSING, 0, "Assim Madibo", "QAT11", "QAT" },
    { MISSING, 0, "Ahmed Fatehi", "QAT12", "QAT" },
    { MISSING, 0, "Team Photo", "QAT13", "QAT" },
    { MISSING, 0, "Mohammed Waad", "QAT14", "QAT" },
    { MISSING, 0, "Abdulaziz Hatem", "QAT15", "QAT" },
    { MISSING, 0, "Hassan Al-Haydos", "QAT16", "QAT" },
    { MISSING, 0, "Edmilson Junior", "QAT17", "QAT" },
    { MISSING, 0, "Akram Hassan Afif", "QAT18", "QAT" },
    { MISSING, 0, "Ahmed Al Ganehi", "QAT19", "QAT" },
    { MISSING, 0, "Almoez Ali", "QAT20", "QAT" },
    { MISSING, 0, "Emblem", "SUI1", "SUI" },
    { MISSING, 0, "Gregor Kobel", "SUI2", "SUI" },
    { MISSING, 0, "Yvon Mvogo", "SUI3", "SUI" },
    { MISSING, 0, "Manuel Akanji", "SUI4", "SUI" },
    { MISSING, 0, "Ricardo Rodriguez", "SUI5", "SUI" },
    { MISSING, 0, "Nico Elvedi", "SUI6", "SUI" },
    { MISSING, 0, "Aurèle Amenda", "SUI7", "SUI" },
    { MISSING, 0, "Silvan Widmer", "SUI8", "SUI" },
    { MISSING, 0, "Granit Xhaka", "SWI9", "SWI" },
    { MISSING, 0, "Denis Zakaria", "SUI10", "SUI" },
    { MISSING, 0, "Remo Freuler", "SUI11", "SUI" },
    { MISSING, 0, "Fabian Rieder", "SUI12", "SUI" },
    { MISSING, 0, "Team Photo", "SUI13", "SUI" },
    { MISSING, 0, "Ardon Jashari", "SUI14", "SUI" },
    { MISSING, 0, "Johan Manzambi", "SUI15", "SUI" },
    { MISSING, 0, "Michel Aebischer", "SUI16", "SUI" },
    { MISSING, 0, "Breel Embolo", "SUI17", "SUI" },
    { MISSING, 0, "Ruben Vargas", "SUI18", "SUI" },
    { MISSING, 0, "Dan Ndoye", "SUI19", "SUI" },
    { MISSING, 0, "Zeki Amdouni", "SWI20", "SWI" },
    { MISSING, 0, "Emblem", "BRA1", "BRA" },
    { MISSING, 0, "Alisson", "BRA2", "BRA" },
    { MISSING, 0, "Bento", "BRA3", "BRA" },
    { MISSING, 0, "Marquinhos", "BRA4", "BRA" },
    { MISSING, 0, "Éder Militão", "BRA5", "BRA" },
    { MISSING, 0, "Gabriel Magalhães", "BRA6", "BRA" },
    { MISSING, 0, "Danilo", "BRA7", "BRA" },
    { MISSING, 0, "Wesley", "BRA8", "BRA" },
    { MISSING, 0, "Lucas Paquetá", "BRA9", "BRA" },
    { MISSING, 0, "Casemiro", "BRA10", "BRA" },
    { MISSING, 0, "Bruno Guimarães", "BRA11", "BRA" },
    { MISSING, 0, "Luiz Henrique", "BRA12", "BRA" },
    { MISSING, 0, "Team Photo", "BRA13", "BRA" },
    { MISSING, 0, "Vinicius Júnior", "BRA14", "BRA" },
    { MISSING, 0, "Rodrygo", "BRA15", "BRA" },
    { MISSING, 0, "João Pedro", "BRA16", "BRA" },
    { MISSING, 0, "Matheus Cunha", "BRA17", "BRA" },
    { MISSING, 0, "Gabriel Martinelli", "BRA18", "BRA" },
    { MISSING, 0, "Raphinha", "BRA19", "BRA" },
    { MISSING, 0, "Estévão", "BRA20", "BRA" },
    { MISSING, 0, "Emblem", "MAR1", "MAR" },
    { MISSING, 0, "Yassine Bounou", "MAR2", "MAR" },
    { MISSING, 0, "Munir El Kajoui", "MAR3", "MAR" },
    { MISSING, 0, "Achraf Hakimi", "MAR4", "MAR" },
    { MISSING, 0, "Noussair Mazraoui", "MAR5", "MAR" },
    { MISSING, 0, "Nayef Aguerd", "MAR6", "MAR" },
    { MISSING, 0, "Roman Saiss", "MAR7", "MAR" },
    { MISSING, 0, "Jawad El Yamio", "MAR8", "MAR" },
    { MISSING, 0, "Adam Masina", "MAR9", "MAR" },
    { MISSING, 0, "Sofyan Amrabat", "MAR10", "MAR" },
    { MISSING, 0, "Azzedine Ounahi", "MAR11", "MAR" },
    { MISSING, 0, "Eliesse Ben Seghir", "MAR12", "MAR" },
    { MISSING, 0, "Team Photo", "MAR13", "MAR" },
    { MISSING, 0, "Bilal El Khannouss", "MAR14", "MAR" },
    { MISSING, 0, "Ismael Saibari", "MAR15", "MAR" },
    { MISSING, 0, "Youssef En-Nesyri", "MAR16", "MAR" },
    { MISSING, 0, "Abde Ezzalzouli", "MAR17", "MAR" },
    { MISSING, 0, "Soufiane Rahimi", "MAR18", "MAR" },
    { MISSING, 0, "Brahim Diaz", "MAR19", "MAR" },
    { MISSING, 0, "Ayoub El Kaabi", "MAR20", "MAR" },
    { MISSING, 0, "Emblem", "HAI1", "HAI" },
    { MISSING, 0, "Johny Placide", "HAI2", "HAI" },
    { MISSING, 0, "Carlens Arcus", "HAI3", "HAI" },
    { MISSING, 0, "Martin Expérience", "HAI4", "HAI" },
    { MISSING, 0, "Jean-Kevin Duverne", "HAI5", "HAI" },
    { MISSING, 0, "Ricardo Adé", "HAI6", "HAI" },
    { MISSING, 0, "Duke Lacroix", "HAI7", "HAI" },
    { MISSING, 0, "Garven Metusala", "HAI8", "HAI" },
    { MISSING, 0, "Hannes Delcroix", "HAI9", "HAI" },
    { MISSING, 0, "Leverton Pierre", "HAI10", "HAI" },
    { MISSING, 0, "Danley Jean Jacques", "HAI11", "HAI" },
    { MISSING, 0, "Jean-Ricner Bellegarde", "HAI12", "HAI" },
    { MISSING, 0, "Team Photo", "HAI13", "HAI" },
    { MISSING, 0, "Christopher Attys", "HAI14", "HAI" },
    { MISSING, 0, "Derrick Etienne Jr", "HAI15", "HAI" },
    { MISSING, 0, "Josue Casimir", "HAI16", "HAI" },
    { MISSING, 0, "Ruben Providence", "HAI17", "HAI" },
    { MISSING, 0, "Duckens Nazon", "HAI18", "HAI" },
    { MISSING, 0, "Louicius Deedson", "HAI19", "HAI" },
    { MISSING, 0, "Frantzdy Pierrot", "HAI20", "HAI" },
    { MISSING, 0, "Emblem", "SCO1", "SCO" },
    { MISSING, 0, "Angus Gunn", "SCO2", "SCO" },
    { MISSING, 0, "Jack Hendry", "SCO3", "SCO" },
    { MISSING, 0, "Kieran Tierney", "SCO4", "SCO" },
    { MISSING, 0, "Aaron Hickey", "SCO5", "SCO" },
    { MISSING, 0, "Andrew Robertson", "SCO6", "SCO" },
    { MISSING, 0, "Scott McKenna", "SCO7", "SCO" },
    { MISSING, 0, "John Souttar", "SCO8", "SCO" },
    { MISSING, 0, "Anthony Ralston", "SCO9", "SCO" },
    { MISSING, 0, "Grant Hanley", "SCO10", "SCO" },
    { MISSING, 0, "Scott McTominay", "SCO11", "SCO" },
    { MISSING, 0, "Billy Gilmour", "SCO12", "SCO" },
    { MISSING, 0, "Team Photo", "SCO13", "SCO" },
    { MISSING, 0, "Lewis Ferguson", "SCO14", "SCO" },
    { MISSING, 0, "Ryan Christie", "SCO15", "SCO" },
    { MISSING, 0, "Kenny McLean", "SCO16", "SCO" },
    { MISSING, 0, "John McGinn", "SCO17", "SCO" },
    { MISSING, 0, "Lyndon Dykes", "SCO18", "SCO" },
    { MISSING, 0, "Che Adams", "SCO19", "SCO" },
    { MISSING, 0, "Ben Gannon-Doak", "SCO20", "SCO" },
    { MISSING, 0, "Emblem", "USA1", "USA" },
    { MISSING, 0, "Math Freese", "USA2", "USA" },
    { MISSING, 0, "Chris Richards", "USA3", "USA" },
    { MISSING, 0, "Tim Ream", "USA4", "USA" },
    { MISSING, 0, "Mark McKenzie", "USA5", "USA" },
    { MISSING, 0, "Alex Freeman", "USA6", "USA" },
    { MISSING, 0, "Antonee Robinson", "USA7", "USA" },
    { MISSING, 0, "Tyler Adams", "USA8", "USA" },
    { MISSING, 0, "Tanner Tessmann", "USA9", "USA" },
    { MISSING, 0, "Weston McKenny", "USA10", "USA" },
    { MISSING, 0, "Christian Roldan", "USA11", "USA" },
    { MISSING, 0, "Timothy Weah", "USA12", "USA" },
    { MISSING, 0, "Team Photo", "USA13", "USA" },
    { MISSING, 0, "Diego Luna", "USA14", "USA" },
    { MISSING, 0, "Malik Tillman", "USA15", "USA" },
    { MISSING, 0, "Christian Pulisic", "USA16", "USA" },
    { MISSING, 0, "Brenden Aaronson", "USA17", "USA" },
    { MISSING, 0, "Ricardo Pepi", "USA18", "USA" },
    { MISSING, 0, "Haji Wright", "USA19", "USA" },
    { MISSING, 0, "Folarin Balogun", "USA20", "USA" },
    { MISSING, 0, "Emblem", "PAR1", "PAR" },
    { MISSING, 0, "Roberto Fernandez", "PAR2", "PAR" },
    { MISSING, 0, "Orlando Gill", "PAR3", "PAR" },
    { MISSING, 0, "Gustavo Gomez", "PAR4", "PAR" },
    { MISSING, 0, "Fabián Balbuena", "PAR5", "PAR" },
    { MISSING, 0, "Juan José Cáceres", "PAR6", "PAR" },
    { MISSING, 0, "Omar Alderete", "PAR7", "PAR" },
    { MISSING, 0, "Junior Alonso", "PAR8", "PAR" },
    { MISSING, 0, "Mathías Villasanti", "PAR9", "PAR" },
    { MISSING, 0, "Diego Gomez", "PAR10", "PAR" },
    { MISSING, 0, "Damián Bobadilla", "PAR11", "PAR" },
    { MISSING, 0, "Andres Cubas", "PAR12", "PAR" },
    { MISSING, 0, "Team Photo", "PAR13", "PAR" },
    { MISSING, 0, "Matias Galarza Fonda", "PAR14", "PAR" },
    { MISSING, 0, "Julio Enciso", "PAR15", "PAR" },
    { MISSING, 0, "Alejandro Romero Gamarra", "PAR16", "PAR" },
    { MISSING, 0, "Miguel Almirón", "PAR17", "PAR" },
    { MISSING, 0, "Ramon Sosa", "PAR18", "PAR" },
    { MISSING, 0, "Angel Romero", "PAR19", "PAR" },
    { MISSING, 0, "Antonio Sanabria", "PAR20", "PAR" },
    { MISSING, 0, "Emblem", "AUS1", "AUS" },
    { MISSING, 0, "Mathew Ryan", "AUS2", "AUS" },
    { MISSING, 0, "Joe Gauci", "AUS3", "AUS" },
    { MISSING, 0, "Harry Souttar", "AUS4", "AUS" },
    { MISSING, 0, "Alessandro Circati", "AUS5", "AUS" },
    { MISSING, 0, "Jordan Bos", "AUS6", "AUS" },
    { MISSING, 0, "Aziz Behich", "AUS7", "AUS" },
    { MISSING, 0, "Cameron Burgess", "AUS8", "AUS" },
    { MISSING, 0, "Lewis Miller", "AUS9", "AUS" },
    { MISSING, 0, "Milos Degenek", "AUS10", "AUS" },
    { MISSING, 0, "Jackson Irvine", "AUS11", "AUS" },
    { MISSING, 0, "Riley McGree", "AUS12", "AUS" },
    { MISSING, 0, "Team Photo", "AUS13", "AUS" },
    { MISSING, 0, "Aiden O'Neill", "AUS14", "AUS" },
    { MISSING, 0, "Connor Metcalfe", "AUS15", "AUS" },
    { MISSING, 0, "Patrick Yazbek", "AUS16", "AUS" },
    { MISSING, 0, "Craig Goodwin", "AUS17", "AUS" },
    { MISSING, 0, "Kusini Vengi", "AUS18", "AUS" },
    { MISSING, 0, "Nestory Irankunda", "AUS19", "AUS" },
    { MISSING, 0, "Mohamed Touré", "AUS20", "AUS" },
    { MISSING, 0, "Emblem", "TUR1", "TUR" },
    { MISSING, 0, "Ugurcan Cakir", "TUR2", "TUR" },
    { MISSING, 0, "Mert Muldur", "TUR3", "TUR" },
    { MISSING, 0, "Zeki Celik", "TUR4", "TUR" },
    { MISSING, 0, "Abdulkerim Bardakci", "TUR5", "TUR" },
    { MISSING, 0, "Caglar Soyuncu", "TUR6", "TUR" },
    { MISSING, 0, "Merih Demiral", "TUR7", "TUR" },
    { MISSING, 0, "Ferdi Kadioglu", "TUR8", "TUR" },
    { MISSING, 0, "Kaan Ayhan", "TUR9", "TUR" },
    { MISSING, 0, "Ismail Yuksek", "TUR10", "TUR" },
    { MISSING, 0, "Hakan Calhanoglu", "TUR11", "TUR" },
    { MISSING, 0, "Orkun Kokcu", "TUR12", "TUR" },
    { MISSING, 0, "Team Photo", "TUR13", "TUR" },
    { MISSING, 0, "Arda Guler", "TUR14", "TUR" },
    { MISSING, 0, "Irfan Can Kahveci", "TUR15", "TUR" },
    { MISSING, 0, "Yunus Akgun", "TUR16", "TUR" },
    { MISSING, 0, "Can Uzun", "TUR17", "TUR" },
    { MISSING, 0, "Baris Alper Yilmaz", "TUR18", "TUR" },
    { MISSING, 0, "Kerem Akturkoglu", "TUR19", "TUR" },
    { MISSING, 0, "Kenan Yildiz", "TUR20", "TUR" },
    { MISSING, 0, "Emblem", "GER1", "GER" },
    { MISSING, 0, "Marc-André ter Stegen", "GER2", "GER" },
    { MISSING, 0, "Jonathan Tah", "GER3", "GER" },
    { MISSING, 0, "David Raum", "GER4", "GER" },
    { MISSING, 0, "Nico Schlotterbeck", "GER5", "GER" },
    { MISSING, 0, "Antonio Rüdiger", "GER6", "GER" },
    { MISSING, 0, "Waldemar Anton", "GER7", "GER" },
    { MISSING, 0, "Ridle Baku", "GER8", "GER" },
    { MISSING, 0, "Maximilian Mittelstadt", "GER9", "GER" },
    { MISSING, 0, "Joshua Kimmich", "GER10", "GER" },
    { MISSING, 0, "Florian Wirtz", "GER11", "GER" },
    { MISSING, 0, "Felix Nmecha", "GER12", "GER" },
    { MISSING, 0, "Team Photo", "GER13", "GER" },
    { MISSING, 0, "Leon Goretzka", "GER14", "GER" },
    { MISSING, 0, "Jamal Musiala", "GER15", "GER" },
    { MISSING, 0, "Serge Gnabry", "GER16", "GER" },
    { MISSING, 0, "Kai Havertz", "GER17", "GER" },
    { MISSING, 0, "Leroy Sane", "GER18", "GER" },
    { MISSING, 0, "Karim Adeyemi", "GER19", "GER" },
    { MISSING, 0, "Nick Woltemade", "GER20", "GER" },
    { MISSING, 0, "Emblem", "CUW1", "CUW" },
    { MISSING, 0, "Eloy Room", "CUW2", "CUW" },
    { MISSING, 0, "Armando Obispo", "CUW3", "CUW" },
    { MISSING, 0, "Sherel Floranus", "CUW4", "CUW" },
    { MISSING, 0, "Jurien Gaari", "CUW5", "CUW" },
    { MISSING, 0, "Joshua Brenet", "CUW6", "CUW" },
    { MISSING, 0, "Roshon Van Eijma", "CUW7", "CUW" },
    { MISSING, 0, "Shurandy Sambo", "CUW8", "CUW" },
    { MISSING, 0, "Livano Comenencia", "CUW9", "CUW" },
    { MISSING, 0, "Godfried Roemeratoe", "CUW10", "CUW" },
    { MISSING, 0, "Juninho Bacuna", "CUW11", "CUW" },
    { MISSING, 0, "Leandro Bacuna", "CUW12", "CUW" },
    { MISSING, 0, "Team Photo", "CUW13", "CUW" },
    { MISSING, 0, "Tahith Chong", "CUW14", "CUW" },
    { MISSING, 0, "Kenji Gorre", "CUW15", "CUW" },
    { MISSING, 0, "Jearl Margaritha", "CUW16", "CUW" },
    { MISSING, 0, "Jurgen Locadia", "CUW17", "CUW" },
    { MISSING, 0, "Jeremy Antonisse", "CUW18", "CUW" },
    { MISSING, 0, "Gervane Kastaneer", "CUW19", "CUW" },
    { MISSING, 0, "Sontje Hansen", "CUW20", "CUW" },
    { MISSING, 0, "Emblem", "CIV1", "CIV" },
    { MISSING, 0, "Yahia Fofana", "CIV2", "CIV" },
    { MISSING, 0, "Ghislain Konan", "CIV3", "CIV" },
    { MISSING, 0, "Wilfried Singo", "CIV4", "CIV" },
    { MISSING, 0, "Odilon Kossounou", "CIV5", "CIV" },
    { MISSING, 0, "Evan Ndicka", "CIV6", "CIV" },
    { MISSING, 0, "Willy Boly", "CIV7", "CIV" },
    { MISSING, 0, "Emmanuel Agbadou", "CIV8", "CIV" },
    { MISSING, 0, "Ousmane Diomande", "CIV9", "CIV" },
    { MISSING, 0, "Franck Kessie", "CIV10", "CIV" },
    { MISSING, 0, "Seko Fofana", "CIV11", "CIV" },
    { MISSING, 0, "Ibrahim Sangare", "CIV12", "CIV" },
    { MISSING, 0, "Team Photo", "CIV13", "CIV" },
    { MISSING, 0, "Jean-Philippe Gbamin", "CIV14", "CIV" },
    { MISSING, 0, "Amad Diallo", "CIV15", "CIV" },
    { MISSING, 0, "Sébastien Haller", "CIV16", "CIV" },
    { MISSING, 0, "Simon Adingra", "CIV17", "CIV" },
    { MISSING, 0, "Yan Diomande", "CIV18", "CIV" },
    { MISSING, 0, "Evann Guessand", "CIV19", "CIV" },
    { MISSING, 0, "Oumar Diakite", "CIV20", "CIV" },
    { MISSING, 0, "Emblem", "ECU1", "ECU" },
    { MISSING, 0, "Hernán Galíndez", "ECU2", "ECU" },
    { MISSING, 0, "Gonzalo Valle", "ECU3", "ECU" },
    { MISSING, 0, "Piero Hincapié", "ECU4", "ECU" },
    { MISSING, 0, "Pervis Estupiñán", "ECU5", "ECU" },
    { MISSING, 0, "Willian Pacho", "ECU6", "ECU" },
    { MISSING, 0, "Ángelo Preciado", "ECU7", "ECU" },
    { MISSING, 0, "Joel Ordóñez", "ECU8", "ECU" },
    { MISSING, 0, "Moises Caicedo", "ECU9", "ECU" },
    { MISSING, 0, "Alan Franco", "ECU10", "ECU" },
    { MISSING, 0, "Kendry Paez", "ECU11", "ECU" },
    { MISSING, 0, "Pedro Vite", "ECU12", "ECU" },
    { MISSING, 0, "Team Photo", "ECU13", "ECU" },
    { MISSING, 0, "John Veboah", "ECU14", "ECU" },
    { MISSING, 0, "Leonardo Campana", "ECU15", "ECU" },
    { MISSING, 0, "Gonzalo Plata", "ECU16", "ECU" },
    { MISSING, 0, "Nilson Angulo", "ECU17", "ECU" },
    { MISSING, 0, "Alan Minda", "ECU18", "ECU" },
    { MISSING, 0, "Kevin Rodriguez", "ECU19", "ECU" },
    { MISSING, 0, "Enner Valencia", "ECU20", "ECU" },
    { MISSING, 0, "Emblem", "NED1", "NED" },
    { MISSING, 0, "Bart Verbruggen", "NED2", "NED" },
    { MISSING, 0, "Virgil van Dijk", "NED3", "NED" },
    { MISSING, 0, "Micky van de Ven", "NED4", "NED" },
    { MISSING, 0, "Jurrien Timber", "NED5", "NED" },
    { MISSING, 0, "Denzel Dumfries", "NED6", "NED" },
    { MISSING, 0, "Nathan Aké", "NED7", "NED" },
    { MISSING, 0, "Jeremie Frimpong", "NED8", "NED" },
    { MISSING, 0, "Jan Paul van Hecke", "NED9", "NED" },
    { MISSING, 0, "Tijjani Reijnders", "NED10", "NED" },
    { MISSING, 0, "Ryan Gravenberch", "NED11", "NED" },
    { MISSING, 0, "Teun Koopmeiners", "NED12", "NED" },
    { MISSING, 0, "Team Photo", "NED13", "NED" },
    { MISSING, 0, "Frenkie de Jong", "NED14", "NED" },
    { MISSING, 0, "Xavi Simons", "NED15", "NED" },
    { MISSING, 0, "Justin Kluivert", "NED16", "NED" },
    { MISSING, 0, "Memphis Depay", "NED17", "NED" },
    { MISSING, 0, "Donyell Malen", "NED18", "NED" },
    { MISSING, 0, "Wout Weghorst", "NED19", "NED" },
    { MISSING, 0, "Cody Gakpo", "NED20", "NED" },
    { MISSING, 0, "Emblem", "JPN1", "JPN" },
    { MISSING, 0, "Zion Suzuki", "JPN2", "JPN" },
    { MISSING, 0, "Henry Heroki Mochizuki", "JPN3", "JPN" },
    { MISSING, 0, "Ayumu Seko", "JPN4", "JPN" },
    { MISSING, 0, "Junnosuke Suzuki", "JPN5", "JPN" },
    { MISSING, 0, "Shogo Taniguchi", "JPN6", "JPN" },
    { MISSING, 0, "Tsuyoshi Watanabe", "JPN7", "JPN" },
    { MISSING, 0, "Kaishu Sano", "JPN8", "JPN" },
    { MISSING, 0, "Yuki Soma", "JPN9", "JPN" },
    { MISSING, 0, "Ao Tanaka", "JPN10", "JPN" },
    { MISSING, 0, "Daichi Kamada", "JPN11", "JPN" },
    { MISSING, 0, "Takefusa Kubo", "JPN12", "JPN" },
    { MISSING, 0, "Team Photo", "JPN13", "JPN" },
    { MISSING, 0, "Ritsu Doan", "JPN14", "JPN" },
    { MISSING, 0, "Keito Nakamura", "JPN15", "JPN" },
    { MISSING, 0, "Takumi Minamino", "JPN16", "JPN" },
    { MISSING, 0, "Shuto Machino", "JPN17", "JPN" },
    { MISSING, 0, "Junya Ito", "JPN18", "JPN" },
    { MISSING, 0, "Koki Ogawa", "JPN19", "JPN" },
    { MISSING, 0, "Ayase Ueda", "JPN20", "JPN" },
    { MISSING, 0, "Emblem", "SWE1", "SWE" },
    { MISSING, 0, "Victor Johansson", "SWE2", "SWE" },
    { MISSING, 0, "Isak Hien", "SWE3", "SWE" },
    { MISSING, 0, "Gabriel Gudmundsson", "SWE4", "SWE" },
    { MISSING, 0, "Emil Holm", "SWE5", "SWE" },
    { MISSING, 0, "Victor Nilsson Lindelöf", "SWE6", "SWE" },
    { MISSING, 0, "Gustaf Lagerbielke", "SWE7", "SWE" },
    { MISSING, 0, "Lucas Bergvall", "SWE8", "SWE" },
    { MISSING, 0, "Hugo Larsson", "SWE9", "SWE" },
    { MISSING, 0, "Jesper Karlström", "SWE10", "SWE" },
    { MISSING, 0, "Yasin Ayari", "SWE11", "SWE" },
    { MISSING, 0, "Mattias Svanberg", "SWE12", "SWE" },
    { MISSING, 0, "Team Photo", "SWE13", "SWE" },
    { MISSING, 0, "Daniel Svensson", "SWE14", "SWE" },
    { MISSING, 0, "Ken Sema", "SWE15", "SWE" },
    { MISSING, 0, "Roony Bardghji", "SWE16", "SWE" },
    { MISSING, 0, "Dejan Kulusevski", "SWE17", "SWE" },
    { MISSING, 0, "Anthony Elanga", "SWE18", "SWE" },
    { MISSING, 0, "Alexander Isak", "SWE19", "SWE" },
    { MISSING, 0, "Viktor Gyökeres", "SWE20", "SWE" },
    { MISSING, 0, "Emblem", "TUN1", "TUN" },
    { MISSING, 0, "Bechir Ben Said", "TUN2", "TUN" },
    { MISSING, 0, "Aymen Dahmen", "TUN3", "TUN" },
    { MISSING, 0, "Yan Valery", "TUN4", "TUN" },
    { MISSING, 0, "Montassar Talbi", "TUN5", "TUN" },
    { MISSING, 0, "Yassine Meriah", "TUN6", "TUN" },
    { MISSING, 0, "Ali Abdi", "TUN7", "TUN" },
    { MISSING, 0, "Dylan Bronn", "TUN8", "TUN" },
    { MISSING, 0, "Ellyes Skhiri", "TUN9", "TUN" },
    { MISSING, 0, "Aissa Laidouni", "TUN10", "TUN" },
    { MISSING, 0, "Ferjani Sassi", "TUN11", "TUN" },
    { MISSING, 0, "Mohamed Ali Ben Romdhane", "TUN12", "TUN" },
    { MISSING, 0, "Team Photo", "TUN13", "TUN" },
    { MISSING, 0, "Hannibal Mejbri", "TUN14", "TUN" },
    { MISSING, 0, "Elias Achouri", "TUN15", "TUN" },
    { MISSING, 0, "Elias Saad", "TUN16", "TUN" },
    { MISSING, 0, "Hazem Mastouri", "TUN17", "TUN" },
    { MISSING, 0, "Ismael Gharbi", "TUN18", "TUN" },
    { MISSING, 0, "Sayfallah Ltaief", "TUN19", "TUN" },
    { MISSING, 0, "Naim Sliti", "TUN20", "TUN" },
    { MISSING, 0, "Emblem", "BEL1", "BEL" },
    { MISSING, 0, "Thibaut Courtois", "BEL2", "BEL" },
    { MISSING, 0, "Arthur Theate", "BEL3", "BEL" },
    { MISSING, 0, "Timothy Castagne", "BEL4", "BEL" },
    { MISSING, 0, "Zeno Debast", "BEL5", "BEL" },
    { MISSING, 0, "Brandon Mechele", "BEL6", "BEL" },
    { MISSING, 0, "Maxim De Cuyper", "BEL7", "BEL" },
    { MISSING, 0, "Thomas Meunier", "BEL8", "BEL" },
    { MISSING, 0, "Youri Tielemans", "BEL9", "BEL" },
    { MISSING, 0, "Amadou Onana", "BEL10", "BEL" },
    { MISSING, 0, "Nicolas Raskin", "BEL11", "BEL" },
    { MISSING, 0, "Alexis Saelemaekers", "BEL12", "BEL" },
    { MISSING, 0, "Team Photo", "BEL13", "BEL" },
    { MISSING, 0, "Hans Vanaken", "BEL14", "BEL" },
    { MISSING, 0, "Kevin De Bruyne", "BEL15", "BEL" },
    { MISSING, 0, "Jérémy Doku", "BEL16", "BEL" },
    { MISSING, 0, "Charles De Ketelaere", "BEL17", "BEL" },
    { MISSING, 0, "Leandro Trossard", "BEL18", "BEL" },
    { MISSING, 0, "Loïs Openda", "BEL19", "BEL" },
    { MISSING, 0, "Romelu Lukaku", "BEL20", "BEL" },
    { MISSING, 0, "Emblem", "EGY1", "EGY" },
    { MISSING, 0, "Mohamed El Shenawy", "EGY2", "EGY" },
    { MISSING, 0, "Mohamed Hany", "EGY3", "EGY" },
    { MISSING, 0, "Mohamed Hamdy", "EGY4", "EGY" },
    { MISSING, 0, "Yasser Ibrahim", "EGY5", "EGY" },
    { MISSING, 0, "Khaled Sobhi", "EGY6", "EGY" },
    { MISSING, 0, "Ramy Rabia", "EGY7", "EGY" },
    { MISSING, 0, "Hossam Abdelmaguid", "EGY8", "EGY" },
    { MISSING, 0, "Ahmed Fatouh", "EGY9", "EGY" },
    { MISSING, 0, "Marwan Attia", "EGY10", "EGY" },
    { MISSING, 0, "Zizo", "EGY11", "EGY" },
    { MISSING, 0, "Hamdy Fathy", "EGY12", "EGY" },
    { MISSING, 0, "Team Photo", "EGY13", "EGY" },
    { MISSING, 0, "Mohamed Lasheen", "EGY14", "EGY" },
    { MISSING, 0, "Emam Ashour", "EGY15", "EGY" },
    { MISSING, 0, "Osama Faisal", "EGY16", "EGY" },
    { MISSING, 0, "Mohamed Salah", "EGY17", "EGY" },
    { MISSING, 0, "Mostafa Mohamed", "EGY18", "EGY" },
    { MISSING, 0, "Trezeguet", "EGY19", "EGY" },
    { MISSING, 0, "Omar Marmoush", "EGY20", "EGY" },
    { MISSING, 0, "Emblem", "IRN1", "IRN" },
    { MISSING, 0, "Alireza Beiranvand", "IRN2", "IRN" },
    { MISSING, 0, "Morteza Pouraliganji", "IRN3", "IRN" },
    { MISSING, 0, "Ehsan Hajsafi", "IRN4", "IRN" },
    { MISSING, 0, "Milad Mohammadi", "IRN5", "IRN" },
    { MISSING, 0, "Shojae Khalilzadeh", "IRN6", "IRN" },
    { MISSING, 0, "Ramin Rezaeian", "IRN7", "IRN" },
    { MISSING, 0, "Hossein Kanaani", "IRN8", "IRN" },
    { MISSING, 0, "Sadegh Moharrami", "IRN9", "IRN" },
    { MISSING, 0, "Saleh Hardani", "IRN10", "IRN" },
    { MISSING, 0, "Saeed Ezatolahi", "IRN11", "IRN" },
    { MISSING, 0, "Saman Ghoddos", "IRN12", "IRN" },
    { MISSING, 0, "Team Photo", "IRN13", "IRN" },
    { MISSING, 0, "Omid Noorafkan", "IRN14", "IRN" },
    { MISSING, 0, "Roozbeh Cheshmi", "IRN15", "IRN" },
    { MISSING, 0, "Mohammad Mohebi", "IRN16", "IRN" },
    { MISSING, 0, "Sardar Azmoun", "IRN17", "IRN" },
    { MISSING, 0, "Mehdi Taremi", "IRN18", "IRN" },
    { MISSING, 0, "Alireza Jahanbakhsh", "IRN19", "IRN" },
    { MISSING, 0, "Ali Gholizadeh", "IRN20", "IRN" },
    { MISSING, 0, "Emblem", "NZL1", "NZL" },
    { MISSING, 0, "Max Crocombe Payne", "NZL2", "NZL" },
    { MISSING, 0, "Alex Paulsen", "NZL3", "NZL" },
    { MISSING, 0, "Michael Boxall", "NZL4", "NZL" },
    { MISSING, 0, "Liberato Cacace", "NZL5", "NZL" },
    { MISSING, 0, "Tim Payne", "NZL6", "NZL" },
    { MISSING, 0, "Tyler Bindon", "NZL7", "NZL" },
    { MISSING, 0, "Francis de Vries", "NZL8", "NZL" },
    { MISSING, 0, "Finn Surman", "NZL9", "NZL" },
    { MISSING, 0, "Joe Bell", "NZL10", "NZL" },
    { MISSING, 0, "Sarpreet Singh", "NZL11", "NZL" },
    { MISSING, 0, "Ryan Thomas", "NZL12", "NZL" },
    { MISSING, 0, "Team Photo", "NZL13", "NZL" },
    { MISSING, 0, "Matthew Garbett", "NZL14", "NZL" },
    { MISSING, 0, "Marko Stamenić", "NZL15", "NZL" },
    { MISSING, 0, "Ben Old", "NZL16", "NZL" },
    { MISSING, 0, "Chris Wood", "NZL17", "NZL" },
    { MISSING, 0, "Elijah Just", "NZL18", "NZL" },
    { MISSING, 0, "Callum McCowatt", "NZL19", "NZL" },
    { MISSING, 0, "Kosta Barbarouses", "NZL20", "NZL" },
    { MISSING, 0, "Emblem", "ESP1", "ESP" },
    { MISSING, 0, "Unai Simon", "ESP2", "ESP" },
    { MISSING, 0, "Robin Le Normand", "ESP3", "ESP" },
    { MISSING, 0, "Aymeric Laporte", "ESP4", "ESP" },
    { MISSING, 0, "Dean Huijsen", "ESP5", "ESP" },
    { MISSING, 0, "Pedro Porro", "ESP6", "ESP" },
    { MISSING, 0, "Dani Carvajal", "ESP7", "ESP" },
    { MISSING, 0, "Marc Cucurella", "ESP8", "ESP" },
    { MISSING, 0, "Martín Zubimendi", "ESP9", "ESP" },
    { MISSING, 0, "Rodri", "ESP10", "ESP" },
    { MISSING, 0, "Pedri", "ESP11", "ESP" },
    { MISSING, 0, "Fabian Ruiz", "ESP12", "ESP" },
    { MISSING, 0, "Team Photo", "ESP13", "ESP" },
    { MISSING, 0, "Mikel Merino", "ESP14", "ESP" },
    { MISSING, 0, "Lamine Yamal", "ESP15", "ESP" },
    { MISSING, 0, "Dani Olmo", "ESP16", "ESP" },
    { MISSING, 0, "Nico Williams", "ESP17", "ESP" },
    { MISSING, 0, "Ferran Torres", "ESP18", "ESP" },
    { MISSING, 0, "Álvaro Morata", "ESP19", "ESP" },
    { MISSING, 0, "Mikel Oyarzabal", "ESP20", "ESP" },
    { MISSING, 0, "Emblem", "CPV1", "CPV" },
    { MISSING, 0, "Vozinha", "CPV2", "CPV" },
    { MISSING, 0, "Logan Costa", "CPV3", "CPV" },
    { MISSING, 0, "Pico", "CPV4", "CPV" },
    { MISSING, 0, "Diney", "CPV5", "CPV" },
    { MISSING, 0, "Steven Moreira", "CPV6", "CPV" },
    { MISSING, 0, "Wagner Pina", "CPV7", "CPV" },
    { MISSING, 0, "Joao Paulo", "CPV8", "CPV" },
    { MISSING, 0, "Yannick Semedo", "CPV9", "CPV" },
    { MISSING, 0, "Kevin Pina", "CPV10", "CPV" },
    { MISSING, 0, "Patrick Andrade", "CPV11", "CPV" },
    { MISSING, 0, "Jamiro Monteiro", "CPV12", "CPV" },
    { MISSING, 0, "Team Photo", "CPV13", "CPV" },
    { MISSING, 0, "Deroy Duarte", "CPV14", "CPV" },
    { MISSING, 0, "Garry Rodrigues", "CPV15", "CPV" },
    { MISSING, 0, "Jovane Cabral", "CPV16", "CPV" },
    { MISSING, 0, "Ryan Mendes", "CPV17", "CPV" },
    { MISSING, 0, "Dailon Livramento", "CPV18", "CPV" },
    { MISSING, 0, "Willy Semedo", "CPV19", "CPV" },
    { MISSING, 0, "Bebe", "CPV20", "CPV" },
    { MISSING, 0, "Emblem", "KSA1", "KSA" },
    { MISSING, 0, "Nawaf Alaqidi", "KSA2", "KSA" },
    { MISSING, 0, "Abdulrahman Al-Sanbi", "KSA3", "KSA" },
    { MISSING, 0, "Saud Abdulhamid", "KSA4", "KSA" },
    { MISSING, 0, "Nawaf Bouwashl", "KSA5", "KSA" },
    { MISSING, 0, "Jihad Thakri", "KSA6", "KSA" },
    { MISSING, 0, "Moteb Al-Harbi", "KSA7", "KSA" },
    { MISSING, 0, "Hassan Altambakti", "KSA8", "KSA" },
    { MISSING, 0, "Musab Aljuwayr", "KSA9", "KSA" },
    { MISSING, 0, "Ziyad Aljohani", "KSA10", "KSA" },
    { MISSING, 0, "Abdullah Alkhaibari", "KSA11", "KSA" },
    { MISSING, 0, "Nasser Aldawsari", "KAS12", "KAS" },
    { MISSING, 0, "Team Photo", "KSA13", "KSA" },
    { MISSING, 0, "Saleh Abu Alshamat", "KSA14", "KSA" },
    { MISSING, 0, "Marwan Alsahafi", "KSA15", "KSA" },
    { MISSING, 0, "Salem Aldawsari", "KSA16", "KSA" },
    { MISSING, 0, "Abdulrahman Al-Aboud", "KSA17", "KSA" },
    { MISSING, 0, "Feras Akbrikan", "KSA18", "KSA" },
    { MISSING, 0, "Saleh Alshehri", "KSA19", "KSA" },
    { MISSING, 0, "Abdullah Al-Hamdan", "KSA20", "KSA" },
    { MISSING, 0, "Emblem", "URU1", "URU" },
    { MISSING, 0, "Sergio Rochet", "URU2", "URU" },
    { MISSING, 0, "Santiago Mele", "URU3", "URU" },
    { MISSING, 0, "Ronald Araujo", "URU4", "URU" },
    { MISSING, 0, "José María Giménez", "URU5", "URU" },
    { MISSING, 0, "Sebastian Caceres", "URU6", "URU" },
    { MISSING, 0, "Mathias Olivera", "URU7", "URU" },
    { MISSING, 0, "Guillermo Varela", "URU8", "URU" },
    { MISSING, 0, "Nahitan Nandez", "URU9", "URU" },
    { MISSING, 0, "Federico Valverde", "URU10", "URU" },
    { MISSING, 0, "Giorgian De Arrascaeta", "URU11", "URU" },
    { MISSING, 0, "Rodrigo Bentancur", "URU12", "URU" },
    { MISSING, 0, "Team Photo", "URU13", "URU" },
    { MISSING, 0, "Manuel Ugarte", "URU14", "URU" },
    { MISSING, 0, "Nicolás de la Cruz", "URU15", "URU" },
    { MISSING, 0, "Maxi Araujo", "URU16", "URU" },
    { MISSING, 0, "Darwin Núñez", "URU17", "URU" },
    { MISSING, 0, "Federico Viñas", "URU18", "URU" },
    { MISSING, 0, "Rodrigo Aguirre", "URU19", "URU" },
    { MISSING, 0, "Facundo Pellistri", "URU20", "URU" },
    { MISSING, 0, "Emblem", "FRA1", "FRA" },
    { MISSING, 0, "Mike Maignan", "FRA2", "FRA" },
    { MISSING, 0, "Theo Hernandez", "FRA3", "FRA" },
    { MISSING, 0, "William Saliba", "FRA4", "FRA" },
    { MISSING, 0, "Jules Kounde", "FRA5", "FRA" },
    { MISSING, 0, "Ibrahima Konate", "FRA6", "FRA" },
    { MISSING, 0, "Dayot Upamecano", "FRA7", "FRA" },
    { MISSING, 0, "Lucas Digne", "FRA8", "FRA" },
    { MISSING, 0, "Aurélien Tchouaméni", "FRA9", "FRA" },
    { MISSING, 0, "Eduardo Camavinga", "FRA10", "FRA" },
    { MISSING, 0, "Manu Kone", "FRA11", "FRA" },
    { MISSING, 0, "Adrien Rabiot", "FRA12", "FRA" },
    { MISSING, 0, "Team Photo", "FRA13", "FRA" },
    { MISSING, 0, "Michael Olise", "FRA14", "FRA" },
    { MISSING, 0, "Ousmane Dembele", "FRA15", "FRA" },
    { MISSING, 0, "Bradley Barcola", "FRA16", "FRA" },
    { MISSING, 0, "Désiré Doué", "FRA17", "FRA" },
    { MISSING, 0, "Kingsley Coman", "FRA18", "FRA" },
    { MISSING, 0, "Hugo Ekitike", "FRA19", "FRA" },
    { MISSING, 0, "Kylian Mbappe", "FRA20", "FRA" },
    { MISSING, 0, "Emblem", "SEN1", "SEN" },
    { MISSING, 0, "Edouard Mendy", "SEN2", "SEN" },
    { MISSING, 0, "Yehvann Diouf", "SEN3", "SEN" },
    { MISSING, 0, "Moussa Niakhaté", "SEN4", "SEN" },
    { MISSING, 0, "Abdoulaye Seck", "SEN5", "SEN" },
    { MISSING, 0, "Ismail Jakobs", "SEN6", "SEN" },
    { MISSING, 0, "El Hadji Malick Diouf", "SEN7", "SEN" },
    { MISSING, 0, "Kalidou Koulibaly", "SEN8", "SEN" },
    { MISSING, 0, "Idrissa Gana Gueye", "SEN9", "SEN" },
    { MISSING, 0, "Pape Matar Sarr", "SEN10", "SEN" },
    { MISSING, 0, "Pape Gueye", "SEN11", "SEN" },
    { MISSING, 0, "Habib Diarra", "SEN12", "SEN" },
    { MISSING, 0, "Team Photo", "SEN13", "SEN" },
    { MISSING, 0, "Lamine Camara", "SEN14", "SEN" },
    { MISSING, 0, "Sadio Mane", "SEN15", "SEN" },
    { MISSING, 0, "Ismaïla Sarr", "SEN16", "SEN" },
    { MISSING, 0, "Boulaye Dia", "SEN17", "SEN" },
    { MISSING, 0, "Iliman Ndiaye", "SEN18", "SEN" },
    { MISSING, 0, "Nicolas Jackson", "SEN19", "SEN" },
    { MISSING, 0, "Krepin Diatta", "SEN20", "SEN" },
    { MISSING, 0, "Emblem", "IRQ1", "IRQ" },
    { MISSING, 0, "Jalal Hassan", "IRQ2", "IRQ" },
    { MISSING, 0, "Rebin Sulaka", "IRQ3", "IRQ" },
    { MISSING, 0, "Hussein Ali", "IRQ4", "IRQ" },
    { MISSING, 0, "Akam Hashem", "IRQ5", "IRQ" },
    { MISSING, 0, "Merchas Doski", "IRQ6", "IRQ" },
    { MISSING, 0, "Zaid Tahseen", "IRQ7", "IRQ" },
    { MISSING, 0, "Manaf Younis", "IRQ8", "IRQ" },
    { MISSING, 0, "Zidane Iqbal", "IRQ9", "IRQ" },
    { MISSING, 0, "Amir Al-Ammari", "IRQ10", "IRQ" },
    { MISSING, 0, "Ibrahim Bavesh", "IRQ11", "IRQ" },
    { MISSING, 0, "Ali Jasim", "IRQ12", "IRQ" },
    { MISSING, 0, "Team Photo", "IRQ13", "IRQ" },
    { MISSING, 0, "Youssef Amyn", "IRQ14", "IRQ" },
    { MISSING, 0, "Aimar Sher", "IRQ15", "IRQ" },
    { MISSING, 0, "Marko Farji", "IRQ16", "IRQ" },
    { MISSING, 0, "Osama Rashid", "IRQ17", "IRQ" },
    { MISSING, 0, "Ali Al-Hamadi", "IRQ18", "IRQ" },
    { MISSING, 0, "Aymen Hussein", "IRQ19", "IRQ" },
    { MISSING, 0, "Mohanad Ali", "IRQ20", "IRQ" },
    { MISSING, 0, "Emblem", "NOR1", "NOR" },
    { MISSING, 0, "Orjan Nyland", "NOR2", "NOR" },
    { MISSING, 0, "Julian Ryerson", "NOR3", "NOR" },
    { MISSING, 0, "Leo Ostigård", "NOR4", "NOR" },
    { MISSING, 0, "Kristoffer Vassbakk Ajer", "NOR5", "NOR" },
    { MISSING, 0, "Marcus Holmgren Pedersen", "NOR6", "NOR" },
    { MISSING, 0, "David Møller Wolfe", "NOR7", "NOR" },
    { MISSING, 0, "Torbjørn Heggem", "NOR8", "NOR" },
    { MISSING, 0, "Morten Thorsby", "NOR9", "NOR" },
    { MISSING, 0, "Martin Ødegaard", "NOR10", "NOR" },
    { MISSING, 0, "Sander Berge", "NOR11", "NOR" },
    { MISSING, 0, "Andreas Schjelderup", "NOR12", "NOR" },
    { MISSING, 0, "Team Photo", "NOR13", "NOR" },
    { MISSING, 0, "Patrick Berg", "NOR14", "NOR" },
    { MISSING, 0, "Erling Haaland", "NOR15", "NOR" },
    { MISSING, 0, "Alexander Sørloth", "NOR16", "NOR" },
    { MISSING, 0, "Aron Dønnum", "NOR17", "NOR" },
    { MISSING, 0, "Jorgen Strand Larsen", "NOR18", "NOR" },
    { MISSING, 0, "Antonio Nusa", "NOR19", "NOR" },
    { MISSING, 0, "Oscar Bobb", "NOR20", "NOR" },
    { MISSING, 0, "Emblem", "ARG1", "ARG" },
    { MISSING, 0, "Emiliano Martinez", "ARG2", "ARG" },
    { MISSING, 0, "Nahuel Molina", "ARG3", "ARG" },
    { MISSING, 0, "Cristian Romero", "ARG4", "ARG" },
    { MISSING, 0, "Nicolas Otamendi", "ARG5", "ARG" },
    { MISSING, 0, "Nicolas Tagliafico", "ARG6", "ARG" },
    { MISSING, 0, "Leonardo Balerdi", "ARG7", "ARG" },
    { MISSING, 0, "Enzo Fernandez", "ARG8", "ARG" },
    { MISSING, 0, "Alexis Mac Allister", "ARG9", "ARG" },
    { MISSING, 0, "Rodrigo De Paul", "ARG10", "ARG" },
    { MISSING, 0, "Exequiel Palacios", "ARG11", "ARG" },
    { MISSING, 0, "Leandro Paredes", "ARG12", "ARG" },
    { MISSING, 0, "Team Photo", "ARG13", "ARG" },
    { MISSING, 0, "Nico Paz", "ARG14", "ARG" },
    { MISSING, 0, "Franco Mastantuono", "ARG15", "ARG" },
    { MISSING, 0, "Nico Gonzalez", "ARG16", "ARG" },
    { MISSING, 0, "Lionel Messi", "ARG17", "ARG" },
    { MISSING, 0, "Lautaro Martinez", "ARG18", "ARG" },
    { MISSING, 0, "Julian Alvarez", "ARG19", "ARG" },
    { MISSING, 0, "Giuliano Simeone", "ARG20", "ARG" },
    { MISSING, 0, "Emblem", "ALG1", "ALG" },
    { MISSING, 0, "Alexis Guendouz", "ALG2", "ALG" },
    { MISSING, 0, "Ramy Bensebaini", "ALG3", "ALG" },
    { MISSING, 0, "Youcef Atal", "ALG4", "ALG" },
    { MISSING, 0, "Rayan Aït-Nouri", "ALG5", "ALG" },
    { MISSING, 0, "Mohamed Amine Tougai", "ALG6", "ALG" },
    { MISSING, 0, "Aïssa Mandi", "ALG7", "ALG" },
    { MISSING, 0, "Ismael Bennacer", "ALG8", "ALG" },
    { MISSING, 0, "Houssem Aquar", "ALG9", "ALG" },
    { MISSING, 0, "Hicham Boudaoui", "ALG10", "ALG" },
    { MISSING, 0, "Ramiz Zerrouki", "ALG11", "ALG" },
    { MISSING, 0, "Nabil Bentalab", "ALG12", "ALG" },
    { MISSING, 0, "Team Photo", "ALG13", "ALG" },
    { MISSING, 0, "Farés Chaibi", "ALG14", "ALG" },
    { MISSING, 0, "Riyad Mahrez", "ALG15", "ALG" },
    { MISSING, 0, "Said Benrahma", "ALG16", "ALG" },
    { MISSING, 0, "Anis Hadj Moussa", "ALG17", "ALG" },
    { MISSING, 0, "Amine Gouiri", "ALG18", "ALG" },
    { MISSING, 0, "Baghdad Bounedjah", "ALG19", "ALG" },
    { MISSING, 0, "Mohammed Amoura", "ALG20", "ALG" },
    { MISSING, 0, "Emblem", "AUT1", "AUT" },
    { MISSING, 0, "Alexander Schlager", "AUT2", "AUT" },
    { MISSING, 0, "Patrick Pentz", "AUT3", "AUT" },
    { MISSING, 0, "David Alaba", "AUT4", "AUT" },
    { MISSING, 0, "Kevin Danso", "AUT5", "AUT" },
    { MISSING, 0, "Philipp Lienhart", "AUT6", "AUT" },
    { MISSING, 0, "Stefan Posch", "AUT7", "AUT" },
    { MISSING, 0, "Phillipp Mwene", "AUT8", "AUT" },
    { MISSING, 0, "Alexander Prass", "AUT9", "AUT" },
    { MISSING, 0, "Xaver Schlager", "AUT10", "AUT" },
    { MISSING, 0, "Marcel Sabitzer", "AUT11", "AUT" },
    { MISSING, 0, "Konrad Laimer", "AUT12", "AUT" },
    { MISSING, 0, "Team Photo", "AUT13", "AUT" },
    { MISSING, 0, "Florian Grillitsch", "AUT14", "AUT" },
    { MISSING, 0, "Nicolas Seiwald", "AUT15", "AUT" },
    { MISSING, 0, "Romano Schmid", "AUT16", "AUT" },
    { MISSING, 0, "Patrick Wimmer", "AUT17", "AUT" },
    { MISSING, 0, "Christoph Baumgartner", "AUT18", "AUT" },
    { MISSING, 0, "Michael Gregoritsch", "AUT19", "AUT" },
    { MISSING, 0, "Marko Arnautović", "AUT20", "AUT" },
    { MISSING, 0, "Emblem", "JOR1", "JOR" },
    { MISSING, 0, "Yazeed Abulaila", "JOR2", "JOR" },
    { MISSING, 0, "Ihsan Haddad", "JOR3", "JOR" },
    { MISSING, 0, "Mohammad Abu Hashish", "JOR4", "JOR" },
    { MISSING, 0, "Yazan Al-Arab", "JOR5", "JOR" },
    { MISSING, 0, "Abdallah Nasib", "JOR6", "JOR" },
    { MISSING, 0, "Saleem Obaid", "JOR7", "JOR" },
    { MISSING, 0, "Mohammad Abualnadi", "JOR8", "JOR" },
    { MISSING, 0, "Ibrahim Saadeh", "JOR9", "JOR" },
    { MISSING, 0, "Nizar Al-Rashdan", "JOR10", "JOR" },
    { MISSING, 0, "Noor Al-Rawabdeh", "JOR11", "JOR" },
    { MISSING, 0, "Mohannad Abu Taha", "JOR12", "JOR" },
    { MISSING, 0, "Team Photo", "JOR13", "JOR" },
    { MISSING, 0, "Amer Jamous", "JOR14", "JOR" },
    { MISSING, 0, "Musa Al-Taamari", "JOR15", "JOR" },
    { MISSING, 0, "Yazan Al-Naimat", "JOR16", "JOR" },
    { MISSING, 0, "Mahmoud Al-Mardi", "JOR17", "JOR" },
    { MISSING, 0, "Ali Olwan", "JOR18", "JOR" },
    { MISSING, 0, "Mohammad Abu Zrayq", "JOR19", "JOR" },
    { MISSING, 0, "Ibrahim Sabra", "JOR20", "JOR" },
    { MISSING, 0, "Emblem", "POR1", "POR" },
    { MISSING, 0, "Diogo Costa", "POR2", "POR" },
    { MISSING, 0, "Jose Sa", "POR3", "POR" },
    { MISSING, 0, "Ruben Dias", "POR4", "POR" },
    { MISSING, 0, "João Cancelo", "POR5", "POR" },
    { MISSING, 0, "Diogo Dalot", "POR6", "POR" },
    { MISSING, 0, "Nuno Mendes", "POR7", "POR" },
    { MISSING, 0, "Gonçalo Inácio", "POR8", "POR" },
    { MISSING, 0, "Bernardo Silva", "POR9", "POR" },
    { MISSING, 0, "Bruno Fernandes", "POR10", "POR" },
    { MISSING, 0, "Ruben Neves", "POR11", "POR" },
    { MISSING, 0, "Vitinha", "POR12", "POR" },
    { MISSING, 0, "Team Photo", "POR13", "POR" },
    { MISSING, 0, "João Neves", "POR14", "POR" },
    { MISSING, 0, "Cristiano Ronaldo", "POR15", "POR" },
    { MISSING, 0, "Francisco Trincao", "POR16", "POR" },
    { MISSING, 0, "João Felix", "POR17", "POR" },
    { MISSING, 0, "Gonçalo Ramos", "POR18", "POR" },
    { MISSING, 0, "Pedro Neto", "POR19", "POR" },
    { MISSING, 0, "Rafael Leão", "POR20", "POR" },
    { MISSING, 0, "Emblem", "COD1", "COD" },
    { MISSING, 0, "Lionel Mpasi", "COD2", "COD" },
    { MISSING, 0, "Aaron Wan-Bissaka", "COD3", "COD" },
    { MISSING, 0, "Axel Tuanzebe", "COD4", "COD" },
    { MISSING, 0, "Arthur Masuaku", "COD5", "COD" },
    { MISSING, 0, "Chancel Mbemba", "COD6", "COD" },
    { MISSING, 0, "Joris Kayembe", "COD7", "COD" },
    { MISSING, 0, "Charles Pickel", "COD8", "COD" },
    { MISSING, 0, "Ngal'ayel Mukau", "COD9", "COD" },
    { MISSING, 0, "Edo Kayembe", "COD10", "COD" },
    { MISSING, 0, "Samuel Moutoussamy", "COD11", "COD" },
    { MISSING, 0, "Noah Sadiki", "COD12", "COD" },
    { MISSING, 0, "Team Photo", "COD13", "COD" },
    { MISSING, 0, "Théo Bongonda", "COD14", "COD" },
    { MISSING, 0, "Meschak Elia", "COD15", "COD" },
    { MISSING, 0, "Yoane Wissa", "COD16", "COD" },
    { MISSING, 0, "Brian Cipenga", "COD17", "COD" },
    { MISSING, 0, "Fiston Mayele", "COD18", "COD" },
    { MISSING, 0, "Cédric Bakambu", "COD19", "COD" },
    { MISSING, 0, "Nathanaël Mbuku", "COD20", "COD" },
    { MISSING, 0, "Emblem", "UZB1", "UZB" },
    { MISSING, 0, "Utkir Yusupov", "UZB2", "UZB" },
    { MISSING, 0, "Farrukh Savfiev", "UZB3", "UZB" },
    { MISSING, 0, "Sherzod Nasrullaev", "UZB4", "UZB" },
    { MISSING, 0, "Umar Eshmurodov", "UZB5", "UZB" },
    { MISSING, 0, "Husniddin Aliqulov", "UZB6", "UZB" },
    { MISSING, 0, "Rustamjon Ashurmatov", "UZB7", "UZB" },
    { MISSING, 0, "Khojiakbar Alijonov", "UZB8", "UZB" },
    { MISSING, 0, "Abdukodir Khusanov", "UZB9", "UZB" },
    { MISSING, 0, "Odiljon Hamrobekov", "UZB10", "UZB" },
    { MISSING, 0, "Otabek Shukurov", "UZB11", "UZB" },
    { MISSING, 0, "Jamshid Iskanderov", "UZB12", "UZB" },
    { MISSING, 0, "Team Photo", "UZB13", "UZB" },
    { MISSING, 0, "Azizbek Turgunboev", "UZB14", "UZB" },
    { MISSING, 0, "Khojimat Erkinov", "UZB15", "UZB" },
    { MISSING, 0, "Eldor Shomurodov", "UZB16", "UZB" },
    { MISSING, 0, "Oston Urunov", "UZB17", "UZB" },
    { MISSING, 0, "Jaloliddin Masharipov", "UZB18", "UZB" },
    { MISSING, 0, "Igor Sergeev", "UZB19", "UZB" },
    { MISSING, 0, "Abbosbek Fayzullaev", "UZB20", "UZB" },
    { MISSING, 0, "Emblem", "COL1", "COL" },
    { MISSING, 0, "Camilo Vargas", "COL2", "COL" },
    { MISSING, 0, "David Ospina", "COL3", "COL" },
    { MISSING, 0, "Dávinson Sánchez", "COL4", "COL" },
    { MISSING, 0, "Yerry Mina", "COL5", "COL" },
    { MISSING, 0, "Daniel Munoz", "COL6", "COL" },
    { MISSING, 0, "Johan Mojica", "COL7", "COL" },
    { MISSING, 0, "Jhon Lucumí", "COL8", "COL" },
    { MISSING, 0, "Santiago Arias", "COL9", "COL" },
    { MISSING, 0, "Jefferson Lerma", "COL10", "COL" },
    { MISSING, 0, "Kevin Castaño", "COL11", "COL" },
    { MISSING, 0, "Richard Rios", "COL12", "COL" },
    { MISSING, 0, "Team Photo", "COL13", "COL" },
    { MISSING, 0, "James Rodriguez", "COL14", "COL" },
    { MISSING, 0, "Juan Fernando Quintero", "COL15", "COL" },
    { MISSING, 0, "Jorge Carrascal", "COL16", "COL" },
    { MISSING, 0, "Jon Arias", "COL17", "COL" },
    { MISSING, 0, "Jhon Cordova", "COL18", "COL" },
    { MISSING, 0, "Luis Suarez", "COL19", "COL" },
    { MISSING, 0, "Luis Diaz", "COL20", "COL" },
    { MISSING, 0, "Emblem", "ENG1", "ENG" },
    { MISSING, 0, "Jordan Pickford", "ENG2", "ENG" },
    { MISSING, 0, "John Stones", "ENG3", "ENG" },
    { MISSING, 0, "Marc Guéhi", "ENG4", "ENG" },
    { MISSING, 0, "Ezri Konsa", "ENG5", "ENG" },
    { MISSING, 0, "Trent Alexander-Arnold", "ENG6", "ENG" },
    { MISSING, 0, "Reece James", "ENG7", "ENG" },
    { MISSING, 0, "Dan Burn", "ENG8", "ENG" },
    { MISSING, 0, "Jordan Henderson", "ENG9", "ENG" },
    { MISSING, 0, "Declan Rice", "ENG10", "ENG" },
    { MISSING, 0, "Jude Bellingham", "ENG11", "ENG" },
    { MISSING, 0, "Cole Palmer", "ENG12", "ENG" },
    { MISSING, 0, "Team Photo", "ENG13", "ENG" },
    { MISSING, 0, "Morgan Rogers", "ENG14", "ENG" },
    { MISSING, 0, "Anthony Gordon", "ENG15", "ENG" },
    { MISSING, 0, "Phil Foden", "ENG16", "ENG" },
    { MISSING, 0, "Bukayo Saka", "ENG17", "ENG" },
    { MISSING, 0, "Harry Kane", "ENG18", "ENG" },
    { MISSING, 0, "Marcus Rashford", "ENG19", "ENG" },
    { MISSING, 0, "Ollie Watkins", "ENG20", "ENG" },
    { MISSING, 0, "Emblem", "CRO1", "CRO" },
    { MISSING, 0, "Dominik Livaković", "CRO2", "CRO" },
    { MISSING, 0, "Duje Caleta-Car", "CRO3", "CRO" },
    { MISSING, 0, "Josko Gvardiol", "CRO4", "CRO" },
    { MISSING, 0, "Josip Stanišić", "CRO5", "CRO" },
    { MISSING, 0, "Luka Vušković", "CRO6", "CRO" },
    { MISSING, 0, "Josip Sutalo", "CRO7", "CRO" },
    { MISSING, 0, "Kristijan Jakic", "CRO8", "CRO" },
    { MISSING, 0, "Luka Modrić", "CRO9", "CRO" },
    { MISSING, 0, "Mateo Kovacic", "CRO10", "CRO" },
    { MISSING, 0, "Martin Baturina", "CRO11", "CRO" },
    { MISSING, 0, "Lovro Majer", "CRO12", "CRO" },
    { MISSING, 0, "Team Photo", "CRO13", "CRO" },
    { MISSING, 0, "Mario Pasalic", "CRO14", "CRO" },
    { MISSING, 0, "Petar Sucic", "CRO15", "CRO" },
    { MISSING, 0, "Ivan Perišić", "CRO16", "CRO" },
    { MISSING, 0, "Marco Pasalic", "CRO17", "CRO" },
    { MISSING, 0, "Ante Budimir", "CRO18", "CRO" },
    { MISSING, 0, "Andrej Kramarić", "CRO19", "CRO" },
    { MISSING, 0, "Franjo Ivanovic", "CRO20", "CRO" },
    { MISSING, 0, "Emblem", "GHA1", "GHA" },
    { MISSING, 0, "Lawrence Ati Zigi", "GHA2", "GHA" },
    { MISSING, 0, "Tariq Lamptey", "GHA3", "GHA" },
    { MISSING, 0, "Mohammed Salisu", "GHA4", "GHA" },
    { MISSING, 0, "Alidu Seidu", "GHA5", "GHA" },
    { MISSING, 0, "Alexander Djiku", "GHA6", "GHA" },
    { MISSING, 0, "Gideon Mensah", "GHA7", "GHA" },
    { MISSING, 0, "Caleb Yirenkyi", "GHA8", "GHA" },
    { MISSING, 0, "Abdul Issahaku Fatawu", "GHA9", "GHA" },
    { MISSING, 0, "Thomas Partey", "GHA10", "GHA" },
    { MISSING, 0, "Salis Abdul Samed", "GHA11", "GHA" },
    { MISSING, 0, "Kamaldeen Sulemana", "GHA12", "GHA" },
    { MISSING, 0, "Team Photo", "GHA13", "GHA" },
    { MISSING, 0, "Mohammed Kudus", "GHA14", "GHA" },
    { MISSING, 0, "Inaki Williams", "GHA15", "GHA" },
    { MISSING, 0, "Jordan Ayew", "GHA16", "GHA" },
    { MISSING, 0, "Andrew Ayew", "GHA17", "GHA" },
    { MISSING, 0, "Joseph Paintsil", "GHA18", "GHA" },
    { MISSING, 0, "Osman Bukari", "GHA19", "GHA" },
    { MISSING, 0, "Antoine Semenyo", "GHA20", "GHA" },
    { MISSING, 0, "Emblem", "PAN1", "PAN" },
    { MISSING, 0, "Orlando Mosquera", "PAN2", "PAN" },
    { MISSING, 0, "Luis Mejia", "PAN3", "PAN" },
    { MISSING, 0, "Fidel Escobar", "PAN4", "PAN" },
    { MISSING, 0, "Andres Andrade", "PAN5", "PAN" },
    { MISSING, 0, "Michael Amir Murillo", "PAN6", "PAN" },
    { MISSING, 0, "Eric Davis", "PAN7", "PAN" },
    { MISSING, 0, "Jose Cordoba", "PAN8", "PAN" },
    { MISSING, 0, "Cesar Blackman", "PAN9", "PAN" },
    { MISSING, 0, "Cristian Martinez", "PAN10", "PAN" },
    { MISSING, 0, "Aníbal Godoy", "PAN11", "PAN" },
    { MISSING, 0, "Adalberto Carrasquilla", "PAN12", "PAN" },
    { MISSING, 0, "Team Photo", "PAN13", "PAN" },
    { MISSING, 0, "Édgar Bárcenas", "PAN14", "PAN" },
    { MISSING, 0, "Carlos Harvey", "PAN15", "PAN" },
    { MISSING, 0, "Ismael Díaz", "PAN16", "PAN" },
    { MISSING, 0, "Jose Fajardo", "PAN17", "PAN" },
    { MISSING, 0, "Cecilio Waterman", "PAN18", "PAN" },
    { MISSING, 0, "Jose Luiz Rodriguez", "PAN19", "PAN" },
    { MISSING, 0, "Alberto Quintero", "PAN20", "PAN" },
    { MISSING, 0, "Italy 1934", "FWC9", "FWC" },
    { MISSING, 0, "Uruguay 1950", "FWC10", "FWC" },
    { MISSING, 0, "West Germany 1954", "FWC11", "FWC" },
    { MISSING, 0, "Brazil 1962", "FWC12", "FWC" },
    { MISSING, 0, "West Germany 1974", "FWC13", "FWC" },
    { MISSING, 0, "Argentina 1986", "FWC14", "FWC" },
    { MISSING, 0, "Brazil 1994", "FWC15", "FWC" },
    { MISSING, 0, "Brazil 2002", "FWC16", "FWC" },
    { MISSING, 0, "Italy 2006", "FWC17", "FWC" },
    { MISSING, 0, "Germany 2014", "FWC18", "FWC" },
    { MISSING, 0, "Argentina 2022", "FWC19", "FWC" },
};

#endif
